### ISSUE TITLE
关于项目语义图

### ISSUE THREAD

**Issue by Ricardo-Ping** [hongyurain/DRAGON#1]
可以问一下项目语义图的建立和GCN传播在哪一块吗，在代码中只发现了用户共现图部分

**Comment by hongyurain** [comment]
Do you mean the construction of item semantic graph? It is under the model folder, dragon.py lines 70-83, which constructs item semantic graph and saves locally. And the GCN code is below line 346.

**Comment by hongyurain** [comment]
> 可以问一下项目语义图的建立和GCN传播在哪一块吗，在代码中只发现了用户共现图部分

Do you mean the construction of item semantic graph? It is under the model folder, dragon.py lines 70-83, which constructs item semantic graph and saves locally. And the GCN code is below line 346.

**Comment by Ricardo-Ping** [comment]
Thanks for your answer. I still have some questions. Can I add your contact information? Meanwhile, I am very interested in your research team, especially Xin Zhou.

**Comment by hongyurain** [comment]
My email address is hongyu006@e.ntu.edu.sg. You can contact Zhou Xin by the email: xin.zhou@ntu.edu.sg
