### ISSUE TITLE
Missing user_graph_dict.npy File in Data Folder

### ISSUE THREAD

**Issue by codeCyw** [hongyurain/DRAGON#2]
Hello, I've downloaded your code from the Dropbox link provided in the 'Readme.md' and I'm planning to run the program. However, I encountered a FileNotFoundError with the message [Errno 2] No such file or directory: '.\\data\\baby\\user_graph_dict.npy'. Upon checking, I noticed that the file is indeed missing from the data folder you provided. Will this file be uploaded later, or is there any other workaround? Thank you.

**Comment by hongyurain** [comment]
In Readme.md, the third point of Run the Code: Run generate-u-u-matrix.py on the dataset you want, to generate the user co-occurrence graph. This Python file is under tools folder, the output is the user_graph_dict.npy file.

**Comment by codeCyw** [comment]
> In Readme.md, the third point of Run the Code: Run generate-u-u-matrix.py on the dataset you want, to generate the user co-occurrence graph. This Python file is under tools folder, the output is the user_graph_dict.npy file.

Thank you very much for your guidance. I have successfully executed the code based on your suggestions. I deeply apologize for any inconvenience my oversight may have caused.
